version: '3'
services:
  api:
    command: npm run test-dev
    build: .
    volumes:
      - ./app:/app
    networks:
      - backend
    ports:
      - "3000:3000"
networks:
  backend:
    driver: bridge
